server:
  port: 7777
  servlet:
    contextPath: /uaa #web基路径

spring:
  application:
    name: auth-server
eureka:
  host: localhost
  port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.host}:${eureka.port}/eureka/
  instance:
      prefer-ip-address: true