server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qizhongju/sc-config.git
          search-paths: sc-config-tutorial
  application:
    name: sc-configserver
